apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    # app.openshift.io/connects-to: '[{"apiVersion":"apps.openshift.io/v1","kind":"DeploymentConfig","name":"postgresql"}]'
    app.openshift.io/connects-to: 'postgresql'
  labels:
    app: product-service
    app.kubernetes.io/part-of: product-backend
    app.openshift.io/runtime: quarkus
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: image-registry.openshift-image-registry.svc:5000/coffeeshop-pipeline/product-service
          envFrom:
            - configMapRef:
                name: product-service-config
            - secretRef:
                name: postgresdb-secret
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 5
status: {}