apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: coffeeshop-prod

resources:
- ../../base/

patchesJson6902:
- path: deployment-frontend.yaml
  target:
    kind: Deployment
    group: apps
    name: coffeeshop
    version: v1