apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: coffeeshop-pipeline

resources:
  - workspaces/source-pvc.yaml
  - workspaces/maven-repo-pvc.yaml
  - pipelines/coffeeshop-pipeline.yaml
  - pipelines/build-n-push-java-pipeline.yaml
