apiVersion: v1
kind: Service
metadata:
  labels:
    app: coffeeshop
    app.kubernetes.io/part-of: coffeeshop
  name: coffeeshop
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: coffeeshop
status:
  loadBalancer: {}