apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  labels:
    template: postgresql-ephemeral-template
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
data:
  database-name: Y29mZmVlc2hvcA==
  database-password: c2hvcDAwMQ==
  database-user: c2hvcA==
type: Opaque
